### ISSUE TITLE
学习方向问题

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#10]
1 我对前端的理解就是，如果是一个网页，最直接展现给用户看到的界面，就是前端，图片，和样式都是前端工程师写的，对于前端呢，我只是晓得这个html，css，js他们的一个区别，具体的就不清楚了
2 后端也就是服务器端，就是写一个网页，网页上面的这些数据来源，就是后端数据库展现出来的，但是后端其实我也只是会基础的curd，稍微复杂的业务的时候，或者稍微复杂的项目的时候，就很吃力了
3 我的决定是还是学前端，因为前端呢，因为这个前端就是可以做出那种好看的网页嘛 我觉得这个做出来 很明显的就可以直接展现到眼前，肯定这个成就感也就大一些

**Comment by frankcjw** [comment]
那我们就已前端的方向开展
