### ISSUE TITLE
前端开启一个新的flutter项目

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#12]
1 如何新建一个项目，建立一个什么类型的项目呢
![图片](https://github.com/user-attachments/assets/c454a66c-8c1a-4149-83e0-30e8622c61fe)
2 这个地方没有看到这个有flutter的项目的选项啊
![图片](https://github.com/user-attachments/assets/a37a40a3-64ea-4eae-ba37-de99a22654ab)
3 https://blog.csdn.net/a942242856/article/details/109556726
根据这个百度引导，在设置里面根本搜不到这个flutter
![图片](https://github.com/user-attachments/assets/5403a30c-6a40-4f5b-a2f3-71db3cd90273)

**Comment by frankcjw** [comment]
![image](https://github.com/user-attachments/assets/8ec349b8-450e-4601-96b9-9716b9a1ccd6)

**Comment by sqp-stack** [comment]
嗯嗯

**Comment by frankcjw** [comment]
idea要装插件

**Comment by sqp-stack** [comment]
1 现在idea插件是装好了的，现在创建这个新的项目界面是没有问题了
![图片](https://github.com/user-attachments/assets/b7e4844e-2a44-40d0-893e-f51ea7aac2b7)
但是我按照百度的弄，还有些东西没有弄出来
2 
![图片](https://github.com/user-attachments/assets/3afe21d9-773a-4845-b4fc-a6f30808c175)
这个 配置这个fluuter的sdk的时候， 一直是点应用这块是点不到，而且点ok以后，也是弄不上去一直
dart也是一样的
![图片](https://github.com/user-attachments/assets/0c658903-1709-4860-a6bc-47dfcea1ac66)
刚刚又好了

**Comment by frankcjw** [comment]
![image](https://github.com/user-attachments/assets/77ccd4fe-46ba-47cb-aa32-20eab00cae3e)


选择flutter 项目啊

**Comment by sqp-stack** [comment]
1  项目是创建玩了，但是卡在了这一步
![图片](https://github.com/user-attachments/assets/9ee19d79-ff37-4d11-bd9d-e1b371fd2838)
idea这个地方是已经下载好了插件的，
![图片](https://github.com/user-attachments/assets/6705f0cc-f2f5-4cf2-aa30-678349353d23)
但是我找不到这个这一步的这个图标，也就不能创建这个虚拟机了

**Comment by frankcjw** [comment]
![image](https://github.com/user-attachments/assets/5a14abc6-a6e3-426e-9e18-5f5e8690e877)


选chrome

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/c3fd6a0d-4d51-4b2f-ac39-849a091b249f)
这个就是我的页面 我看不到这个图标 所以就无法创建这个虚拟机

**Comment by frankcjw** [comment]
> ![图片](https://private-user-images.githubusercontent.com/189966560/391459097-c3fd6a0d-4d51-4b2f-ac39-849a091b249f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMjcwMzYsIm5iZiI6MTczMzEyNjczNiwicGF0aCI6Ii8xODk5NjY1NjAvMzkxNDU5MDk3LWMzZmQ2YTBkLTRkNTEtNGIyZi1hYzM5LTg0OWEwOTFiMjQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwODA1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWY2YWVmYzVhMmVjMzQyYTM0YjY4ZmExMmFmYWIwNjE2NzU2NGZkNzA5NjlhNjFhNzk0ZDMwMzRkMmEyZWNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vZq--wax0IZSyq6nVgG-MPnkubO2OeNwUe9pfKBV4_8) 这个就是我的页面 我看不到这个图标 所以就无法创建这个虚拟机

你没安卓环境

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/cb835827-fbab-45d5-919d-f2ecaa1f6282)
![图片](https://github.com/user-attachments/assets/7d566ea7-0e15-4e4f-a20c-72cbf1e38b99)
![图片](https://github.com/user-attachments/assets/336b466c-2452-4007-84e9-8daf37b6f6c1)
运行完了 然后就是这个样子

**Comment by frankcjw** [comment]
启动成功!
