### ISSUE TITLE
第一个dart网页面书写

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#15]
我说哈我自己的思路，首先应该是是一个大组件，装下这三个子组件，这三个子组件呈现垂直排布，所以我觉得可以是这个Column组件，然后再对分别对这三个子组件，进行依次的写
问题1 这3个子组件，又分别用什么组件呢，可以第一个用row吗，也就是组件里面是可以套其它组件吗，
问题2 这个Container 可以用吗 具体又该怎么用到这个里面呢
问题3 也不算问题，就是我不熟悉这些代码，写起来语法很多会用错，

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/c52bd5cf-d5aa-4661-94a7-dca96ecf05fe)
正在看这个布局组件，以及在做对应的笔记

**Comment by frankcjw** [comment]
1. 组件可以嵌套
2. Container 就是一个框,可以加样式
3. 多写

另外

1. 写的代码和页面效果截图
2. 尝试在纸上先把想要用的组件画出来

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/c52bd5cf-d5aa-4661-94a7-dca96ecf05fe)
正在看这个布局组件，以及在做对应的笔记

**Comment by sqp-stack** [comment]
> 1. 组件可以嵌套
> 
>     2. Container 就是一个框,可以加样式
> 
>     3. 多写
> 
> 
> 另外
> 
>     1. 写的代码和页面效果截图
> 
>     2. 尝试在纸上先把想要用的组件画出来

嗯嗯要的

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/491489ef-2568-4b66-9e54-fce84abdd0de)

**Comment by frankcjw** [comment]
Text Container组件先用起来

**Comment by frankcjw** [comment]
children 里面是放组件数组

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/8d5afc50-1fa2-44b3-9fc2-d13db548f71c)

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/a8551100-4a45-4f18-a072-b74d2a78e360)
还有点问题

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/6348879c-9807-472b-9189-e93120609903)

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/488cc02a-c125-405f-8d98-2c26067e675a)
我把这个字体和这四个全部放在了这个column里面 我现在需要将这个安全筹码字体 弄到和这个左对齐，也就是说要弄到这个column这个组件的左对齐，最好设置一个内边距，反正就是要和这个给的图案一样的，但是我已经设置了这个左对齐 还是不行

**Comment by sqp-stack** [comment]
[
[README.md](https://github.com/user-attachments/files/17990423/README.md)
![图片](https://github.com/user-attachments/assets/cc20a12e-ae35-44f1-8de0-c398f2f7c655)

问题：1  现在做的这个网页怎么达到像竖着的状态，而不是像现在这样左右两边都撑满的状态
       2 如何达到下面还留下一大部分，现在的状态就是三个container已经撑满了这个网页面了

**Comment by frankcjw** [comment]
1. 网页是可以拉伸,调整尺寸
2. 试下用singlescrollview

**Comment by sqp-stack** [comment]
[README.md](https://github.com/user-attachments/files/17991046/README.md)
问的了哈ai关于上面问题如何解决的情况，分别给这三个container外面套了一个padding组件，改变边距的作用，也加了一个留白的组件，但是结果如下图所示（这个是放在大显示屏上面看到的截图）
![图片](https://github.com/user-attachments/assets/f98c5e5f-1420-4081-946c-cd732f715a90)
放在小的显示屏截图又所示
![图片](https://github.com/user-attachments/assets/01e38ca9-120a-44f9-98a7-960da2a28549)
问题1 为什么会出现这样的情况呢？
        2  到底应该用什么办法来解决当前这个问题呢，解决这个将页面调整成手机竖屏的，感觉代码层面是改变不了

**Comment by frankcjw** [comment]
1. 为什么说的是什么

**Comment by frankcjw** [comment]
2 页面是自适应,尝试使用`singlescrollview`

**Comment by sqp-stack** [comment]
[README.md](https://github.com/user-attachments/files/17994111/README.md)
我重新把整个页面中最大的column这个组件的最外层套了一个singlescrollview组件，结果如图所示，没有实现滑动的效果，不理解为什么会出现这个效果
![图片](https://github.com/user-attachments/assets/0dc962e3-6ef1-44c4-a140-38647e9dd2db)
对于这个问题 我刚刚进行了ai问，ai给的解释是如下，并且给出了解决办法
![图片](https://github.com/user-attachments/assets/18014302-841a-4671-8d5c-7ad1c8d00ba1)
但是我使用了两个解决办法都不行，一个是给
![图片](https://github.com/user-attachments/assets/224f566f-de38-404d-b5b0-c60670179086)
还有一个解决办法是
![图片](https://github.com/user-attachments/assets/4c0b558d-64f6-4620-bd69-e53b9bc082e4)
两个解决办法 都试过了 但是依然还是一样，画面没有变化如下所示
![图片](https://github.com/user-attachments/assets/324ada63-980f-4bc9-bfe0-0e2c47e75a8b)
然后下面是我根据ai提示改过的代码，麻烦你看看诶，这个下面的代码我更新的就是为column中的子组件加了这个Flexible 自适应高度，但是依然还是没有解决看到这个column下面所以子组件的问题
[README.md](https://github.com/user-attachments/files/17994690/README.md)

**Comment by frankcjw** [comment]
查看`Expanded`的具体解释

**Comment by frankcjw** [comment]
另外截图flutter里面的报错 并解释

**Comment by sqp-stack** [comment]
> 查看`Expanded`的具体解释

嗯嗯 但是我使用的是这个Flexible，

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/c9c36c06-cd12-4646-b46b-95a1cf4d2f84)
![图片](https://github.com/user-attachments/assets/e92e9a36-5db1-4f24-88c9-23ff13ead40b)
![图片](https://github.com/user-attachments/assets/42da78cf-7d59-472a-8780-c4a1b7d85239)
不理解这个解释什么意思呢，我只是在这三个container外面分别加了这个Flexible组件，怎么会报错关于这个RenderBox 没有被正确布局的错呢

**Comment by frankcjw** [comment]
![image](https://github.com/user-attachments/assets/d5943fa8-25d6-4c73-9ae2-b41762208fc8)


用你自己的思路解释.

**Comment by frankcjw** [comment]
> 查看`Expanded`的具体解释

这个

**Comment by sqp-stack** [comment]
> > 查看`Expanded`的具体解释
> 
> 这个

嗯嗯

**Comment by sqp-stack** [comment]
> ![image](https://private-user-images.githubusercontent.com/6236022/392187988-d5943fa8-25d6-4c73-9ae2-b41762208fc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzUxNDgsIm5iZiI6MTczMzI3NDg0OCwicGF0aCI6Ii82MjM2MDIyLzM5MjE4Nzk4OC1kNTk0M2ZhOC0yNWQ2LTRjNzMtOWFlMi1iNDE3NjIyMDhmYzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDExNDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjQ5ZDczYmIxYzhiN2NiMmIzODI0YTYzMWRkM2M1ZjE5NzNjNWIzNGJkMTU3YjAxZWIzNmM3NTg2NzI5Y2UyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vnDlumNSdTC1cZRLkusNdpqldl0gsYR_0HTPBRDRUZk)
> 
> 用你自己的思路解释.

我自己的思路的话，就是说这个RenderBox组件不能被放置了，没用空间被放置了，不能正常布局，导致这个flutter在渲染的时候出现了问题，但是具体为什么会导致这个出现 我就不晓得了诶

**Comment by sqp-stack** [comment]
> `Expanded`

![图片](https://github.com/user-attachments/assets/c4f1ca4b-4b24-4d2a-b067-671352f7c48b)
![图片](https://github.com/user-attachments/assets/8135d518-c22a-4485-9b51-795c724cf795)
我的网页现在情况 放在小的网页界面，实际上是装不下这个大的column的，才会出现这个就是原来那个黄黄的东西，而Expanded组件是将其子组件自动填充这个父组件剩下空间，页面父组件是column，子组件三个container，但是根本没有剩下的空间，所以选择用的Flexible去让这三个container自动按比例去分配这个父组件即是这个column

**Comment by frankcjw** [comment]
两个概念

1. column有参数是mainSize,可以是max或则是min,max是撑满
2. singlescrollview本身就是一个可以包括超出屏幕范围的组件

所以singlescrollview包裹column,里面不能用expand之类的组件,

**无限长度当然不能套无限长度**

**Comment by sqp-stack** [comment]
> 两个概念
> 
>     1. column有参数是mainSize,可以是max或则是min,max是撑满
> 
>     2. singlescrollview本身就是一个可以包括超出屏幕范围的组件
> 
> 
> 所以singlescrollview包裹column,里面不能用expand之类的组件,
> 
> **无限长度当然不能套无限长度**

嗯嗯好的

**Comment by sqp-stack** [comment]
> > 两个概念
> > ```
> > 1. column有参数是mainSize,可以是max或则是min,max是撑满
> > 
> > 2. singlescrollview本身就是一个可以包括超出屏幕范围的组件
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以singlescrollview包裹column,里面不能用expand之类的组件,
> > **无限长度当然不能套无限长度**
> 
> 嗯嗯好的

我现在把这个expand之类的组件去掉了

**Comment by sqp-stack** [comment]
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_svg/flutter_svg.dart';

void main() {
  runApp(const NiLuoPage());
}

class NiLuoPage extends StatelessWidget {
  const NiLuoPage({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        // Root widget
        home: Scaffold(
      appBar: AppBar(
        title: const Text("小尼诺"),
        centerTitle: true, // 是文字居中显示
      ),
      body: SingleChildScrollView(
          child: Padding(
        padding: EdgeInsets.all(20.0),
        child: Column(
          children: [
            //身体上面部分
            Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                // 让所有子组件横向填满父容器
                children: [
                  Padding(
                    //外层加一个padding，目的是给每个 Container 添加了左右和上下的间距，确保它们不撑满整个屏幕宽度，同时也不影响容器内的子组件排版。
                    padding:
                        EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
                    child: Container(
                      //为第一个整体加入一个，从而增加外边框颜色
                      decoration: BoxDecoration(
                          border: Border.all(
                        color: Colors.grey, //加边框颜色
                        width: 1.0,
                      )),
                      //padding: ,
                      child: Column(
                        //整体的第一个
                        crossAxisAlignment: CrossAxisAlignment.start, // 左对齐

                        children: [
                          Container(
                            padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                            child: Text(
                              "安全统筹",
                              style: TextStyle(
                                  fontSize: 16, fontWeight: FontWeight.bold),
                              //textAlign: TextAlign.left,
                            ),
                          ),
                          SizedBox(height: 20),
                          SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: Row(
                              // 装的下面四个矢量图标

                              mainAxisAlignment: MainAxisAlignment.start,
                              // 让其子组件水平对齐到左侧

                              children: [
                                Container(
                                  // 第一个图标
                                  color: Colors.red,
                                  width: 50, // 设置宽度
                                  height: 50, // 设置高度
                                  margin: EdgeInsets.only(
                                      left: 16.0), // 给第一个图标加和左边的间距
                                ),
                                SizedBox(width: 300), // 控制图标之间的间距
                                Container(
                                  color: Colors.orange,
                                  width: 50,
                                  height: 50,
                                ),
                                SizedBox(width: 300),
                                Container(
                                  color: Colors.green,
                                  width: 50,
                                  height: 50,
                                ),
                                SizedBox(width: 200),
                                Container(
                                  color: Colors.yellow,
                                  width: 50,
                                  height: 50,
                                ),
                              ],
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                  SizedBox(height: 50.0),
                  Padding(
                    padding:
                        EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
                    child: Container(
                      //为第二个个整体加入一个，从而增加外边框颜色

                      decoration: BoxDecoration(
                          border: Border.all(
                        color: Colors.grey, //加边框颜色
                        width: 1.0,
                      )),
                      //padding: ,
                      child: Column(
                        //整体的第二个
                        crossAxisAlignment: CrossAxisAlignment.start,
                        // 使这个column下的子组件左对齐
                        children: [
                          Container(
                            padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                            child: Text(
                              "我的服务",
                              style: TextStyle(
                                  fontSize: 16, fontWeight: FontWeight.bold),
                              //textAlign: TextAlign.left,
                            ),
                          ),
                          SizedBox(height: 20),
                          SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: Row(
                              // 装的下面四个矢量图标

                              mainAxisAlignment: MainAxisAlignment.start,
                              // 让其子组件水平对齐到左侧

                              children: [
                                Container(
                                  // 第一个图标
                                  color: Colors.red,
                                  width: 50, // 设置宽度
                                  height: 50, // 设置高度
                                  margin: EdgeInsets.only(
                                      left: 16.0), // 给第一个图标加和左边的间距
                                ),
                                SizedBox(width: 300), // 控制图标之间的间距
                                Container(
                                  color: Colors.orange,
                                  width: 50,
                                  height: 50,
                                ),
                                SizedBox(width: 300),
                                Container(
                                  color: Colors.green,
                                  width: 50,
                                  height: 50,
                                ),
                                SizedBox(width: 200),
                                Container(
                                  color: Colors.yellow,
                                  width: 50,
                                  height: 50,
                                ),
                              ],
                            ),
                          ),
                          SizedBox(height: 20),
                          SingleChildScrollView(
                            scrollDirection: Axis.horizontal,
                            child: Row(
                              // 第二排的下面两个矢量图标
                              children: [
                                Container(
                                  // 第一个图标
                                  color: Colors.red,
                                  width: 50, // 设置宽度
                                  height: 50, // 设置高度
                                  margin: EdgeInsets.only(
                                      left: 16.0), // 给第一个图标加和左边的间距
                                ),
                                SizedBox(width: 300), // 控制图标之间的间距
                                Container(
                                  color: Colors.orange,
                                  width: 50,
                                  height: 50,
                                ),
                              ],
                            ),
                          )
                        ],
                      ),
                    ),
                  ),
                  SizedBox(height: 50.0),
                  Padding(
                    padding:
                        EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
                    child: Container(
                      //为第三个整体加入一个，从而增加外边框颜色

                      //给每个 Container 添加了左右和上下的间距，确保它们不撑满整个屏幕宽度，同时也不影响容器内的子组件排版。
                      decoration: BoxDecoration(
                          border: Border.all(
                        color: Colors.grey, //加边框颜色
                        width: 1.0,
                      )),
                      width: double.infinity,
                      // 设置宽度为 infinity，使其左右宽度撑满最外面这一层的 Column
                      //padding: ,
                      child: SingleChildScrollView(
                        scrollDirection: Axis.horizontal,
                        child: Column(
                          //整体的第三个
                          crossAxisAlignment: CrossAxisAlignment.start,
                          // 左对齐

                          children: [
                            Container(
                              padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                              child: Text(
                                "推荐服务",
                                style: TextStyle(
                                    fontSize: 15, fontWeight: FontWeight.bold),
                                //textAlign: TextAlign.left,
                              ),
                            ),
                            SizedBox(height: 15),
                            Container(
                              padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                              child: Text(
                                "查知实验室",
                                style: TextStyle(
                                    fontSize: 20, fontWeight: FontWeight.bold),
                                //textAlign: TextAlign.left,
                              ),
                            ),
                            SizedBox(height: 15),
                            Container(
                              padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                              child: Text(
                                "合作专区",
                                style: TextStyle(
                                    fontSize: 16, fontWeight: FontWeight.bold),
                                //textAlign: TextAlign.left,
                              ),
                            ),
                            SizedBox(height: 15),
                            Container(
                              padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                              child: Text(
                                "帮助与反馈",
                                style: TextStyle(
                                    fontSize: 20, fontWeight: FontWeight.bold),
                                //textAlign: TextAlign.left,
                              ),
                            ),
                            SizedBox(height: 15),
                            Container(
                              padding: EdgeInsets.all(8.0), // 可以为文本添加一些边距
                              child: Text(
                                "退出登录",
                                style: TextStyle(
                                    fontSize: 16, fontWeight: FontWeight.bold),
                                //textAlign: TextAlign.left,
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                  // 使用Expanded来让容器占满可用空间，并保留底部空白
                ]),
            // 底部导航栏
            Padding(
                padding:
                EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),
                child:  Container(
                  height: 100.0,
                  decoration: BoxDecoration(
                      border: Border.all(
                        color: Colors.grey, //加边框颜色
                        width: 1.0,
                      )),
                  child: Row(
                      mainAxisAlignment: MainAxisAlignment.center, // 水平居中
                      children: [
                        Container(
                          // 第一个图标
                          color: Colors.red,
                          width: 50, // 设置宽度
                          height: 50, // 设置高度
                          margin:
                          EdgeInsets.only(left: 16.0), // 给第一个图标加和左边的间距
                        ),
                        SizedBox(width: 300), // 控制图标之间的间距
                        Container(
                          color: Colors.orange,
                          width: 50,
                          height: 50,
                        ),
                      ]) ,),
              ) ,

          ],
        ),
      )),
    ));
  }
}

**Comment by sqp-stack** [comment]
代码还有个细节问题，底部导航栏这个container，放在小页面上面，可以正常显示在底部，但是放在大屏幕上面就不完全显示在底部了
![图片](https://github.com/user-attachments/assets/1339dbfc-b020-418a-a9dc-f2a2ec0af719)
自己尝试过使用 使用 Stack 来布局内容，并且使用Positioned来作为底部导航栏container组件的父组件，但是还是没有解决这个问题

**Comment by frankcjw** [comment]
**不同问题分不同issue**

1. container撑满需要设置宽高,查`mediaquery`

**Comment by sqp-stack** [comment]
> **不同问题分不同issue**
> 
>     1. container撑满需要设置宽高,查`mediaquery`

嗯嗯 我心想都是关于写这个页面的问题，就没有分开
