### ISSUE TITLE
idea里面配置Androidsdk问题

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#18]
我现在想在idea里面配置一个安卓的模拟器，已经成功下载了这个Androidsdk，但是在idea里面配置新增这个sdk的时候，一直无法新增上去，原因是什么呢
![图片](https://github.com/user-attachments/assets/1d994908-40c7-42c8-83fc-942697a6c18f)
如上图所示， 我点了OK以后，什么反应都没有，也没有新增上去

**Comment by frankcjw** [comment]
安装`android-studio-2024.2.1.10-windows`

**Comment by sqp-stack** [comment]
> 安装`android-studio-2024.2.1.10-windows`

意思是说不用idea写前端代码了吗

**Comment by frankcjw** [comment]
装这个软件会自动配置好安卓环境.文档有写

**Comment by sqp-stack** [comment]
> 装这个软件会自动配置好安卓环境.文档有写
嗯嗯 好的 我已经装好了的  我再试看看用idea可以不 不行就用这个写Android写代码

**Comment by frankcjw** [comment]
是用`idea`,**不是**用`android-studio`

**Comment by frankcjw** [comment]
@sqp-stack 安卓有时候需要用梯子,国内网络可能会下载不了,所以先用网页的调试  后续再尝试使用安卓环境
