### ISSUE TITLE
搭建flutter应用开发环境，并且配置Androidstudio模拟器

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#24]
1 配置jdk，并且配置环境变量
2 安装Androidstudio软件，其中包含了下载这个Androidsdk（就是开发这个安卓应用需要用的包，包含了这个安卓模拟器），但是这一步我在下载的时候一直卡着， 如下图所示
![图片](https://github.com/user-attachments/assets/a5bacbe6-97a2-4523-bbaa-22a6a9f4ca09)
耐心等待只能
3 配置这个Androidsdk的环境变量
4 然后flutter doctor验证是否配置好
报错的时候，其中有个是
![图片](https://github.com/user-attachments/assets/39d0a11c-b9eb-4d5d-bbef-02b66f3eed13)
信号灯提示连接失败，该了文件的链接配置，然后再执行flutter doctor命令，注意（次地方不能使用代理，不然回一直卡着不动）
5 然后就是创建项目，再创建模拟器
具体的步骤见网址：https://blog.csdn.net/huaqianzkh/article/details/138345049

**Comment by frankcjw** [comment]
### 注意

记录`软件`,`sdk`的版本号

可能包括`jdk`,`as`,`dart`,`flutter`的版本

**Comment by sqp-stack** [comment]
as版本使用的是20242.1，fluttersdk是3.24.3，jdk使用的是1.8

**Comment by sqp-stack** [comment]
遇到一个很糟糕的问题
以前我是从网上去直接下载的这个Androidsdk，然后配置到这个as上面的，然后就可以直接创建模拟器一步一步的成功
但是这次我选择直接安装这个as的时候，我就发现他是在去自己下载这个Androidsdk的，如下图所示，我点的是标准版本的
![图片](https://github.com/user-attachments/assets/dfda8b8d-2fbd-4c44-9ddc-3850e1ed31c5)
然后就把这个Androidsdk下载到c盘下面自动了的
as里面也自动的配置了这个sdk的目录
最后我来创建模拟器的时候，卡在了这个选择模拟器上面具体原因如下图百度所示
![图片](https://github.com/user-attachments/assets/018a9af8-982d-48a5-b58f-08a62e7ff399)
![图片](https://github.com/user-attachments/assets/8894d0f7-35d7-4aad-9489-fa0b1570e19d)
这里说是下载对应的这个镜像，但是问题就是到底哪个是对应的呢
后面我还是选了一个如下图所示，点击下载
![图片](https://github.com/user-attachments/assets/279b8cc8-4888-488d-9ab1-08fde760a486)
但是又一直卡在着，或者说不是卡这，而是一直很慢的下载，如下图所示
![图片](https://github.com/user-attachments/assets/7acfff03-e4bd-4846-846f-e729beb2ce90)
这是为什么原因就是那么慢呢

**Comment by frankcjw** [comment]
下载很慢 很正常. 梯子过去就会很慢

**Comment by sqp-stack** [comment]
搭建模拟器的时候，需要注意的一点就是，第一次将flutter项目运行到这个模拟器的时候，加载会比较慢，因为gradlle会去国外的服务器里面下载这个安卓相关的依赖，需要耐心的等久一点的
