### ISSUE TITLE
Androidsdk和镜像的区别是什么呢

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#25]
我搜索说这个镜像差不多就是安卓操作系统的意思嘛，Androidsdk就是包含了模拟器，包含了这个镜像的，我点击这个创建模拟器的时候，选择设备的时候，有些设备选择了以后，也是提示没有这个镜像，喊我必须选择一个，要去下载对应的镜像，我可以理解其实这个sdk只是包含了大部分设备的操作系统和镜像嘛 有一部分其实还是没有包含的哈，使用还是要去自己下载的嘛

**Comment by frankcjw** [comment]
1. 翻译sdk全称 
2. 镜像可以理解为系统文件

**Comment by sqp-stack** [comment]
> 1. 翻译sdk全称
> 
>     2. 镜像可以理解为系统文件

嗯嗯我大概理解了
