### ISSUE TITLE
错误内容

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#8]
1 一般要进入一个公司的项目的话，都是会给我分配一个账号和密码，然后我进去以后，就可以直接像通过如下图方式直接拉去
![图片](https://github.com/user-attachments/assets/c5ac1651-694d-4202-91e6-41633c5e1a4d)
2 昨天通过这个sshkey 是不需要这个密码和账号就可以直接进入公司项目的，但是我的账号和密码都是自己注册的，就相当于是个完全的空的代码厂库
![图片](https://github.com/user-attachments/assets/37fd39de-af06-4c91-aba1-fd8f2e0f66ff)
3 然后我随机搜了一个项目，试着通过https那个url直接复制，然后到idea里面去就可以拉去下来，说明这个拉去是可以的，只是因为我其实根本就还没有进入到这个公司的代码库里面去，所以无论怎么搜 都找不到这个项目的
![图片](https://github.com/user-attachments/assets/147942df-bb8a-409b-8c08-02c1c0838ca1)
通过将这个项目的url复制到这里就可以直接拉下来项目

4 网页直接访问的这个项目的时候，提示的错误信息如下图
![图片](https://github.com/user-attachments/assets/1a1ac107-0b93-4548-96bd-b348b14dca75)
直接报错 找不到这个项目的

**Comment by frankcjw** [comment]
直接git clone  用ssh的方式clone

**Comment by sqp-stack** [comment]
1 首先，这是使用的是ssh的方式进行拉去代码的时候，保证公钥已经添加到了这个github上
2,只是晓得这个https的url，就要转为成为这个ssh url，这一步问的ai
![图片](https://github.com/user-attachments/assets/9c43b866-dc8c-4711-8def-0d1e443d0b2d)
3 然后在创建好的文件夹里面打开git的终端，输入git clone sshurl,拉去代码成功
