### ISSUE TITLE
启动项目问题

### ISSUE THREAD

**Issue by sqp-stack** [chazhikeji/training#9]
1 使用maven导入依赖的时候，我使用的是阿里云的仓库，但是有个依赖阿里云厂库是没有的，如下所示
![图片](https://github.com/user-attachments/assets/c27cbcad-6795-430f-a0b2-0498aba37b47)
![图片](https://github.com/user-attachments/assets/01d50225-eb45-4f93-a033-c1da5cb7cf6e)
2 具体在那个厂库找，我没有找到的

**Comment by frankcjw** [comment]
私有部署仓库,拖不下来我发你安装包

**Comment by sqp-stack** [comment]
1 、导入这个jar文件的时候，使用的是mvn install 命令去将这个.jar文件下载到本地厂库的，但是我使用idea的这个终端输入这个命令的时候，就报错，如图所示
![图片](https://github.com/user-attachments/assets/9dc36756-028d-43e5-9544-8b36563ec8c7)
查了哈，说没有配置环境变量，我去配置了的，而且我使用的是maven3.3.9版本的，怎么可能会报这个错呢，而且我去配置了
m2_HOME这个变量以后，还是一样的报这个错
2 、 然后我再使用这个win+cmd打开这个终端的时候，再次输入相同的命令，我就又把这个文件下载到本地场库，难道这两个终端不是一样的吗，为什么会有这个差别呢

**Comment by frankcjw** [comment]
翻译截图的报错信息

**Comment by sqp-stack** [comment]
翻译了的  喊我设置这个maven的环境变量，但是我用的maven版本是3.3.9
![图片](https://github.com/user-attachments/assets/d57ce2e5-5e61-4b14-91e7-14ca1ee436e1)
![图片](https://github.com/user-attachments/assets/ddd50786-4656-4b8e-9ff7-b16aa2bbc53a)
而且我也配置了这个环境变量，并且我在这个win+cmd的终端下面是可以看到自己的maven版本的，
![图片](https://github.com/user-attachments/assets/581226a9-261b-43f2-8084-53ac90739b3a)
而且同样的，这个mvn -v的命令在idea的终端下面输入的时候还是会报一样的错。如下图

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/b71dc49d-0b3c-43db-aed8-1812e7f7759b)

**Comment by sqp-stack** [comment]
1 
![图片](https://github.com/user-attachments/assets/0b8ad026-f43e-4848-8f9a-6919028ec3f9)
无法访问这个类，查了哈ai，
![图片](https://github.com/user-attachments/assets/1fc2e28d-e214-42d7-9a1a-b1f52f1af295)
项目里面有这个依赖的，
![图片](https://github.com/user-attachments/assets/418b3667-8f49-4807-a33d-e284eb2cfb42)
其余就是喊重启idea清理缓存，reload maven 这些方法都试过了

2 我怀疑的话 是不是没有启动这个redis呢

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/a257dd8c-c5a1-4d5f-acc7-43be7cc7e949)
我百度问了哈 ，这个是一致的啊，那为什么会出现刚刚上面那种不同的报错呢

**Comment by sqp-stack** [comment]
刚刚那个redis的问题，我直接点击启动类然后运行报错如下，然后ai问了哈，说的是jdk版本的问题
![图片](https://github.com/user-attachments/assets/6b743982-acc8-4b9a-9837-930ed99c9649)
然后再次重新启动整个项目，暂时这个错误没有报了

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/b432017e-1a10-45eb-8922-e403fc895216)
启动的时候，报错 意思就是说什么yml格式有错误，编码错误什么的，但是我检查了的话，编码是没有问题的，但是这个格式的话，也没有错啊，没有什么空格什么的，还有就是这个中文字符，都是打了注解的， 不可以会识别到啊，所以跟中午字符也没有关系啊
如下图是ai的解释
![图片](https://github.com/user-attachments/assets/a873f189-0fa5-4fbc-af94-c9c1a81fc3f2)

**Comment by frankcjw** [comment]
刚刚是否有拉过代码?

尝试删除项目 重新拉代码 

下午我修改过配置文件

**Comment by sqp-stack** [comment]
![图片](https://github.com/user-attachments/assets/0c4a0f5d-08aa-4a75-ad50-cb29526ea1c5)
我重新用这个软件验证了哈，yml是没有问题的

**Comment by sqp-stack** [comment]
> 刚刚是否有拉过代码?
> 
> 尝试删除项目 重新拉代码
> 
> 下午我修改过配置文件

嗯嗯好的

**Comment by frankcjw** [comment]
```
--spring.profiles.active=chazhidev
```

启动配置加上上面的配置



![image](https://github.com/user-attachments/assets/377e7c8b-3453-4e0e-998f-9ede613a33bd)

**Comment by sqp-stack** [comment]
> > 刚刚是否有拉过代码?
> > 尝试删除项目 重新拉代码
> > 下午我修改过配置文件
> 
> 嗯嗯好的

意思就是说直接把这个项目全部删了 重新拉去一次哈

**Comment by frankcjw** [comment]
> > > 刚刚是否有拉过代码?
> > > 尝试删除项目 重新拉代码
> > > 下午我修改过配置文件
> > 
> > 
> > 嗯嗯好的
> 
> 意思就是说直接把这个项目全部删了 重新拉去一次哈

是的. 用`master`分支

**Comment by sqp-stack** [comment]
> > > > 刚刚是否有拉过代码?
> > > > 尝试删除项目 重新拉代码
> > > > 下午我修改过配置文件
> > > 
> > > 
> > > 嗯嗯好的
> > 
> > 
> > 意思就是说直接把这个项目全部删了 重新拉去一次哈
> 
> 是的. 用`master`分支

还是用那个克隆的方式嘛 跟原来一样的方式哈

**Comment by sqp-stack** [comment]
> JDK17

我用的是jdk1.8 是必须要用jdk17对吧

**Comment by frankcjw** [comment]
> > > > > 刚刚是否有拉过代码?
> > > > > 尝试删除项目 重新拉代码
> > > > > 下午我修改过配置文件
> > > > 
> > > > 
> > > > 嗯嗯好的
> > > 
> > > 
> > > 意思就是说直接把这个项目全部删了 重新拉去一次哈
> > 
> > 
> > 是的. 用`master`分支
> 
> 还是用那个克隆的方式嘛 跟原来一样的方式哈

是的

**Comment by sqp-stack** [comment]
你给我的那个网站 打不开诶
![图片](https://github.com/user-attachments/assets/2b6e9425-03d6-47f8-90e0-21ced1c17bbe)
我下载一个2023版本的也可以吧

**Comment by frankcjw** [comment]
> 你给我的那个网站 打不开诶 ![图片](https://private-user-images.githubusercontent.com/189966560/391377793-2b6e9425-03d6-47f8-90e0-21ced1c17bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDEzODIsIm5iZiI6MTczMzEwMTA4MiwicGF0aCI6Ii8xODk5NjY1NjAvMzkxMzc3NzkzLTJiNmU5NDI1LTAzZDYtNDdmOC05MGUwLTIxY2VkMWMxN2JiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMlQwMDU4MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MWNlOWIyNTllNDU4NzdmOTFhZGY1OWRmOWYzZGVlZjY1NmEyYzk0YmJjZmUzZjY0MWRhMmMyMTYyNWQ5YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pvt2qOBslKcU2k_4bXC2i6fsZO5f94DWoBiU0U2Bqoo) 我下载一个2023版本的也可以吧

这个是软件版本啊

**Comment by sqp-stack** [comment]
嗯嗯

**Comment by sqp-stack** [comment]
1 启动项目的时候，报错如图
![图片](https://github.com/user-attachments/assets/7089babc-ed18-492c-ad55-c35d533c23d4)
百度显示是我的idea版本是2020，版本过低导致和这个jdk17不匹配，所以就需要下载一个这个高版本的idea

**Comment by frankcjw** [comment]
1. 翻译上面的文字
2. 确认是不匹配吗?
3. 后续都使用最新的软件

**Comment by sqp-stack** [comment]
> 1. 翻译上面的文字
> 
>     2. 确认是不匹配吗?
> 
>     3. 后续都使用最新的软件
我百度的时候，他说的是这个原因导致的，我现在就是在下载这个2024版本

**Comment by sqp-stack** [comment]
遇到一个问题，
![图片](https://github.com/user-attachments/assets/c9efb69d-b174-40b3-ad85-5b1cd3999b8b)
我查了哈 就是这个pom文件里面没有办法导入这个依赖，但是我这个新版本的idea 很奇怪的就是这个pom文件就是直接点不进去的那种
